export const LABELS = {
  GOOGLE_LOGIN: `Sign in with google`,
  SIGN_IN: `Sign In`,
  SIGN_UP: `Sign Up`,
  UPLOAD: `UPLOAD`,
  NO_AC: `Don't have an Account?`,
  YES_AC: `Have an Account`,
  FORGOT_PASS: `Forgot Password?`,
  CREATE_LISTING: "Create Listing",
  DELETE_USER: "Delete Account",
  SIGN_OUT: " Sign out",
  CREATE_LISTING_HEADING: "Create a listing of property",
  CREATE_LIST: "Create List",
  LISTING_IMG_UPLOAD_WARNING:
    "The first image will be the cover (max 6 allowed)",
  SPECIFICATIONS: "Specifications:",
  BEDROOMS: "Bed Rooms",
  BATHROOMS: "Bathrooms",
  HALL: "Hall",
  REGULAR_PRICE: "Regular Price",
  REGULAR_PRICE_SUB: "(Rs/ month)",
  DISCOUNT_PRICE: "Discount Price",
  DISCOUNT_PRICE_SUB: "(Rs/ month)",
  IMAGE: "Image :",
  PARKING: "Parking Spot",
  POOL: "Swimming Pool",
  FULL: " Full Furnished",
  SEMI: "Semi-Furnished",
  NOT: " Unfurnished",
};
